---

- name: Create Gitlab data directory
  ansible.builtin.file:
    path: "{{ docker_compose_gitlab_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Template a gitlab docker-compose file
  ansible.builtin.template:
    src: templates/docker-compose-gitlab.yaml.j2
    dest: "{{ docker_compose_services_directory }}/{{ docker_compose_gitlab_file_name }}"
  notify: Start/Restart Gitlab

- name: Flush handlers
  meta: flush_handlers
