# Docker & docker compose
docker_users:
  - admin
# Docker Compose Plugin options.
docker_install_compose_plugin: false
# Docker Compose options.
docker_install_compose: true
docker_compose_version: "v2.27.1"

# Node exporter
node_exporter_version: 1.8.1

# Test variables
test_name: all
