---

- name: Monitoring directories
  block:
    - name: Create prometheus data directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_prometheus_data_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: Create prometheus config directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_prometheus_config_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: Create prometheus alert rules directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_prometheus_config_dir }}/rules"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: Create grafana data directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_grafana_data_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: Create grafana provisioning directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_grafana_config_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: Create grafana datasources directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_grafana_config_dir }}/datasources"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create grafana dashboards directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_grafana_config_dir }}/dashboards"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: Create alertmanager config directory
      ansible.builtin.file:
        path: "{{ docker_compose_templates_alertmanager_config_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      when: docker_compose_templates_alertmanager

- name: Define monitoring docker compose file name
  set_fact:
    docker_compose_templates_monitoring_file_name: "monitoring.yaml"

- name: Template monitoring docker-compose file
  ansible.builtin.template:
    src: templates/monitoring.yaml.j2
    dest: "{{ docker_compose_templates_directory }}/{{ docker_compose_templates_monitoring_file_name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    # mode: 0744
  # notify: Start/Restart monitoring stack

- name: Template prometheus configuration file
  ansible.builtin.template:
    src: templates/prometheus/prometheus-config.yml.j2
    dest: "{{ docker_compose_templates_prometheus_config_dir }}/prometheus.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    # mode: 0744
  notify: Reload prometheus config

- name: Copy prometheus alert rules
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_compose_templates_prometheus_config_dir }}/rules/{{ item | basename | regex_replace('\\.yaml','') }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_fileglob:
    - ../templates/prometheus/rules/*.yaml
  notify: Reload prometheus config

- name: Template grafana config file
  ansible.builtin.template:
    src: templates/grafana/config.monitoring.j2
    dest: "{{ docker_compose_services_config_base_path }}/grafana/config.monitoring"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    # mode: 0744
  # notify: Start/Restart monitoring stack

- name: Template grafana datasource file
  ansible.builtin.template:
    src: templates/grafana/provisioning/datasources.yaml.j2
    dest: "{{ docker_compose_templates_grafana_config_dir }}/datasources/datasources.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    # mode: 0744
  # notify: Start/Restart monitoring stack

- name: Template alertmanager configuration file
  ansible.builtin.template:
    src: templates/alertmanager/config.yml.j2
    dest: "{{ docker_compose_templates_alertmanager_config_dir }}/config.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  notify: Reload alertmanager config

- name: Copy alertmanager message template
  ansible.builtin.copy:
    src: ../templates/alertmanager/telegram.tmpl
    dest: "{{ docker_compose_templates_alertmanager_config_dir }}/telegram.tmpl"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  notify: Reload alertmanager config

- name: Flush handlers
  meta: flush_handlers
