---

- name: Start/Restart Homepage
  ansible.builtin.command:
    cmd: "docker compose -f {{ docker_compose_homepage_file_name }} up -d --force-recreate"
    chdir: "{{ docker_compose_services_directory }}"
  become: yes
  when: docker_compose_homepage_start
