---
docker_compose_homepage_start: true
docker_compose_homepage_file_name: "homepage.yaml"

docker_compose_homepage_image_version: latest
docker_compose_homepage_config_dir: "{{ docker_compose_services_config_directory }}/homepage"
docker_compose_homepage_labels: []
