---

- name: Create Vaultwarden data directory
  ansible.builtin.file:
    path: "{{ docker_compose_vaultwarden_data_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Get user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ ansible_user }}"

- name: Template Vaultwarden docker-compose file
  ansible.builtin.template:
    src: templates/docker-compose-vaultwarden.yaml.j2
    dest: "{{ docker_compose_services_directory }}/{{ docker_compose_vaultwarden_file_name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  notify: Start/Restart Vaultwarden

- name: Flush handlers
  meta: flush_handlers
