- hosts: storage-node
  roles:
    - role: traefik
      tags: [ traefik ]
    - role: prometheus-stack
      tags: [ monitoring ]
    - role: vaultwarden
      tags: [ vaultwarden ]
    - role: immich
      tags: [ immich ]

- import_playbook: ../ops/docker-cleanup.yaml                                                                                                             
  vars:                                                                                                                                                   
    target_hosts: storage-node
