---

- name: Start/Restart Paperless
  ansible.builtin.command:
    cmd: "docker compose -f {{ docker_compose_paperless_file_name }} up -d"
    chdir: "{{ docker_compose_services_directory }}"
  when: docker_compose_paperless_start
