---
docker_compose_gitlab_stack_start: true
docker_compose_gitlab_file_name: "gitlab.yaml"

docker_compose_gitlab_image_version: latest
docker_compose_gitlab_dir: "/opt/gitlab"
docker_compose_gitlab_domain: "gitlab-test.{{ docker_compose_services_domain }}"
docker_compose_gitlab_registry_domain: "gitlab-registry-test.{{ docker_compose_services_domain }}"
docker_compose_gitlab_root_password:
docker_compose_gitlab_labels: []
