---
docker_compose_prometheus_stack_start: true
docker_compose_prometheus_monitoring_file_name: "monitoring.yaml"

docker_compose_services_data_directory: "/opt"

# prometheus
docker_compose_prometheus_image_version: latest
docker_compose_prometheus_data_dir: "{{ docker_compose_services_data_directory }}/prometheus"
docker_compose_prometheus_config_dir: "{{ docker_compose_services_config_directory }}/prometheus"
docker_compose_prometheus_scrape_config_node_exporter_targets: ""
docker_compose_prometheus_scrape_config_smartctl_exporter_targets: ""
docker_compose_prometheus_scrape_config_cadvisor_targets: ""
docker_compose_prometheus_domain: "prometheus.{{ docker_compose_services_domain }}"
docker_compose_prometheus_labels: []

# grafana
docker_compose_prometheus_grafana_image_version: latest
docker_compose_prometheus_grafana_data_dir: "{{ docker_compose_services_data_directory }}/grafana"
docker_compose_prometheus_grafana_config_dir: "{{ docker_compose_services_config_directory }}/grafana/provisioning"
docker_compose_prometheus_grafana_admin_password: ""
docker_compose_prometheus_grafana_domain: "grafana.{{ docker_compose_services_domain }}"
docker_compose_prometheus_grafana_labels: []

# alertmanager
docker_compose_prometheus_alertmanager: true
docker_compose_prometheus_alertmanager_image_version: latest
docker_compose_prometheus_alertmanager_config_dir: "{{ docker_compose_services_config_directory }}/alertmanager"
docker_compose_prometheus_alertmanager_telegram_bot_token: ""
docker_compose_prometheus_alertmanager_telegram_chat_id: ""
docker_compose_prometheus_alertmanager_domain: "alertmanager.{{ docker_compose_services_domain }}"
docker_compose_prometheus_alertmanager_labels: []
